# Generated by Django 6.0.1 on 2026-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Others', 'Others')], max_length=50),
        ),
    ]
