# Generated by Django 6.0.1 on 2026-01-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
