# Generated by Django 6.0.1 on 2026-01-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_usersettings_two_factor_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='two_factor_enabled',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hide_amount',
            field=models.BooleanField(default=False),
        ),
    ]
