# Generated by Django 6.0.1 on 2026-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_usersettings_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='hide_amount',
            new_name='hide_amounts',
        ),
    ]
